---
abstract: 'A Perl wrapper for the OANDA Exchange Rates API'
author:
  - 'Dave Doyle <ddoyle@oanda.com>'
build_requires:
  Data::Dumper: '0'
  HTTP::Response: '0'
  Module::Spy: '0'
  Test::Fatal: '0'
  Test::More: '0.88'
  Test::Pod::Coverage: '0'
  URI: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WebService-OANDA-ExchangeRates
requires:
  JSON::XS: '0'
  LWP::UserAgent: '0'
  Moo: '0'
  Try::Tiny: '0'
  Type::Tiny: '0'
  Types::URI: '0'
resources:
  homepage: https://github.com/oanda/perl-webservice-oanda-exchangerates
  repository: https://github.com/oanda/perl-webservice-oanda-exchangerates.git
version: '0.003'
